### ISSUE TITLE
Solid Slack Bridge (milestone wrapup)

### ISSUE THREAD

**Issue by michielbdejong** [solid-contrib/data-modules#7]
https://github.com/pondersource/solid-slack-bridge

Reza will publish this in the Slack marketplace, and then we'll list it as a 3000 euro milestone.

**Comment by michielbdejong** [comment]
It seems there were some blockers both with getting two-way sync working and with publishing to the Slack marketplace.
To do: discuss with @yasharpm

**Comment by michielbdejong** [comment]
I'll test this now and then refactor it a bit so we can package it as part of the Chat data module.

**Comment by michielbdejong** [comment]
I'll hold off on refactoring the Solid-accessing code, in light of https://github.com/solid-contrib/data-modules/issues/135
But I'll work on:
* [ ] https://github.com/tubsproject/solid-slack-bridge/issues/8
* [ ] https://github.com/tubsproject/solid-slack-bridge/issues/14
* [ ] https://github.com/tubsproject/solid-slack-bridge/issues/9
* [ ] https://github.com/tubsproject/solid-slack-bridge/issues/10
* [ ] https://github.com/tubsproject/solid-slack-bridge/issues/11
* [ ] https://github.com/tubsproject/solid-slack-bridge/issues/12
* [ ] https://github.com/tubsproject/solid-slack-bridge/issues/13

**Comment by michielbdejong** [comment]
It's hard to know how perfect I want to make this before calling it done.
I now worked 36 specifically on Solid-Slack-Bridge and its rewrite into the start of the TUBS framework. The milestone is for 60 hours and although I did a lot of unplanned work on Pivot, it would feel better to spend another 20 hours or so on the rest of the goals listed.

I created a screencast of how far I got with it: https://youtu.be/MnMe7zvQvBo
Compared with [the work that @yasharpm  and @soltanireza65  did last year](), this is mainly:
* me getting familiar with the code, how it interacts with Solid, and how it interacts with Slack
* code refactoring (splitting out the Solid client but not actually splitting out the Slack client)
* adding a database backend (although I didn't yet include unit tests and a database schema for it)

I'll hold off on submitting the RfP so I can improve it further.
